// Package all imports all the commands
package all

import (
	// Active commands
	_ "github.com/miseyu/rclone/cmd"
	_ "github.com/miseyu/rclone/cmd/authorize"
	_ "github.com/miseyu/rclone/cmd/cat"
	_ "github.com/miseyu/rclone/cmd/check"
	_ "github.com/miseyu/rclone/cmd/cleanup"
	_ "github.com/miseyu/rclone/cmd/cmount"
	_ "github.com/miseyu/rclone/cmd/config"
	_ "github.com/miseyu/rclone/cmd/copy"
	_ "github.com/miseyu/rclone/cmd/copyto"
	_ "github.com/miseyu/rclone/cmd/cryptcheck"
	_ "github.com/miseyu/rclone/cmd/cryptdecode"
	_ "github.com/miseyu/rclone/cmd/dbhashsum"
	_ "github.com/miseyu/rclone/cmd/dedupe"
	_ "github.com/miseyu/rclone/cmd/delete"
	_ "github.com/miseyu/rclone/cmd/genautocomplete"
	_ "github.com/miseyu/rclone/cmd/gendocs"
	_ "github.com/miseyu/rclone/cmd/info"
	_ "github.com/miseyu/rclone/cmd/listremotes"
	_ "github.com/miseyu/rclone/cmd/ls"
	_ "github.com/miseyu/rclone/cmd/ls2"
	_ "github.com/miseyu/rclone/cmd/lsd"
	_ "github.com/miseyu/rclone/cmd/lsjson"
	_ "github.com/miseyu/rclone/cmd/lsl"
	_ "github.com/miseyu/rclone/cmd/md5sum"
	_ "github.com/miseyu/rclone/cmd/memtest"
	_ "github.com/miseyu/rclone/cmd/mkdir"
	_ "github.com/miseyu/rclone/cmd/mount"
	_ "github.com/miseyu/rclone/cmd/move"
	_ "github.com/miseyu/rclone/cmd/moveto"
	_ "github.com/miseyu/rclone/cmd/ncdu"
	_ "github.com/miseyu/rclone/cmd/obscure"
	_ "github.com/miseyu/rclone/cmd/purge"
	_ "github.com/miseyu/rclone/cmd/rcat"
	_ "github.com/miseyu/rclone/cmd/rmdir"
	_ "github.com/miseyu/rclone/cmd/rmdirs"
	_ "github.com/miseyu/rclone/cmd/serve"
	_ "github.com/miseyu/rclone/cmd/sha1sum"
	_ "github.com/miseyu/rclone/cmd/size"
	_ "github.com/miseyu/rclone/cmd/sync"
	_ "github.com/miseyu/rclone/cmd/tree"
	_ "github.com/miseyu/rclone/cmd/version"
)
